export const file = [
  {
    name: "File 1",
    subject: "Subject",
    id: "1",
    date_created: "10/12/23",
    date_accessed: "10/13/23",
    text: "sdjlkfsldkj sdjlkfsldkj sdjlkfsldkj sdjlkfsldkj sdjlkfsldkj sdjlkfsldkj sdjlkfsldkjsdjlkfsldkj sdjlkfsldkj sdjlkfsldkj sdjlkfsldkj sdjlkfsldkj sdjlkfsldkj sdjlkfsldkj sdjlkfsldkj sdjlkfsldkj sdjlkfsldkjsdjlkfsldkj sdjlkfsldkj sdjlkfsldkj sdjlkfsldkj sdjlkfsldkj sdjlkfsldkj sdjlkfsldkj sdjlkfsldkj sdjlkfsldkj sdjlkfsldkjsdjlkfsldkj sdjlkfsldkj sdjlkfsldkj sdjlkfsldkj sdjlkfsldkj sdjlkfsldkj sdjlkfsldkj sdjlkfsldkj sdjlkfsldkj sdjlkfsldkjsdjlkfsldkj sdjlkfsldkj sdjlkfsldkj sdjlkfsldkj sdjlkfsldkj sdjlkfsldkj sdjlkfsldkj sdjlkfsldkj sdjlkfsldkj sdjlkfsldkjsdjlkfsldkj sdjlkfsldkj sdjlkfsldkjsdjlkfsldkj sdjlkfsldkj sdjlkfsldkj sdjlkfsldkj sdjlkfsldkj sdjlkfsldkj sdjlkfsldkjsdjlkfsldkj sdjlkfsldkj sdjlkfsldkjsdjlkfsldkj sdjlkfsldkj sdjlkfsldkj sdjlkfsldkj sdjlkfsldkj sdjlkfsldkj sdjlkfsldkjsdjlkfsldkj sdjlkfsldkj sdjlkfsldkjsdjlkfsldkj sdjlkfsldkj sdjlkfsldkj sdjlkfsldkj sdjlkfsldkj sdjlkfsldkj sdjlkfsldkjsdjlkfsldkj sdjlkfsldkj sdjlkfsldkjsdjlkfsldkj sdjlkfsldkj sdjlkfsldkj sdjlkfsldkj sdjlkfsldkj sdjlkfsldkj sdjlkfsldkjsdjlkfsldkj sdjlkfsldkj sdjlkfsldkjsdjlkfsldkj sdjlkfsldkj sdjlkfsldkj sdjlkfsldkj sdjlkfsldkj sdjlkfsldkj sdjlkfsldkjsdjlkfsldkj sdjlkfsldkj sdjlkfsldkjsdjlkfsldkj sdjlkfsldkj sdjlkfsldkj sdjlkfsldkj sdjlkfsldkj sdjlkfsldkj sdjlkfsldkjsdjlkfsldkj sdjlkfsldkj sdjlkfsldkj",
  },
  {
    name: "File 2",
    subject: "Subject",
    id: "2",
    date_created: "10/12/23",
    date_accessed: "10/13/23",
    text: "sdjlkfsldkj sdjlkfsldkj sdjlkfsldkj sdjlkfsldkj sdjlkfsldkj sdjlkfsldkj sdjlkfsldkjsdjlkfsldkj sdjlkfsldkj sdjlkfsldkj sdjlkfsldkj sdjlkfsldkj sdjlkfsldkj sdjlkfsldkj sdjlkfsldkj sdjlkfsldkj sdjlkfsldkjsdjlkfsldkj sdjlkfsldkj sdjlkfsldkj sdjlkfsldkj sdjlkfsldkj sdjlkfsldkj sdjlkfsldkj sdjlkfsldkj sdjlkfsldkj sdjlkfsldkjsdjlkfsldkj sdjlkfsldkj sdjlkfsldkj sdjlkfsldkj sdjlkfsldkj sdjlkfsldkj sdjlkfsldkj sdjlkfsldkj sdjlkfsldkj sdjlkfsldkjsdjlkfsldkj sdjlkfsldkj sdjlkfsldkj sdjlkfsldkj sdjlkfsldkj sdjlkfsldkj sdjlkfsldkj sdjlkfsldkj sdjlkfsldkj sdjlkfsldkjsdjlkfsldkj sdjlkfsldkj sdjlkfsldkjsdjlkfsldkj sdjlkfsldkj sdjlkfsldkj sdjlkfsldkj sdjlkfsldkj sdjlkfsldkj sdjlkfsldkjsdjlkfsldkj sdjlkfsldkj sdjlkfsldkjsdjlkfsldkj sdjlkfsldkj sdjlkfsldkj sdjlkfsldkj sdjlkfsldkj sdjlkfsldkj sdjlkfsldkjsdjlkfsldkj sdjlkfsldkj sdjlkfsldkjsdjlkfsldkj sdjlkfsldkj sdjlkfsldkj sdjlkfsldkj sdjlkfsldkj sdjlkfsldkj sdjlkfsldkjsdjlkfsldkj sdjlkfsldkj sdjlkfsldkjsdjlkfsldkj sdjlkfsldkj sdjlkfsldkj sdjlkfsldkj sdjlkfsldkj sdjlkfsldkj sdjlkfsldkjsdjlkfsldkj sdjlkfsldkj sdjlkfsldkjsdjlkfsldkj sdjlkfsldkj sdjlkfsldkj sdjlkfsldkj sdjlkfsldkj sdjlkfsldkj sdjlkfsldkjsdjlkfsldkj sdjlkfsldkj sdjlkfsldkjsdjlkfsldkj sdjlkfsldkj sdjlkfsldkj sdjlkfsldkj sdjlkfsldkj sdjlkfsldkj sdjlkfsldkjsdjlkfsldkj sdjlkfsldkj sdjlkfsldkj",
  },
  {
    name: "File 3",
    subject: "Subject",
    id: "3",
    date_created: "10/12/23",
    date_accessed: "10/13/23",
    text: "sdjlkfsldkj sdjlkfsldkj sdjlkfsldkj sdjlkfsldkj sdjlkfsldkj sdjlkfsldkj sdjlkfsldkjsdjlkfsldkj sdjlkfsldkj sdjlkfsldkj sdjlkfsldkj sdjlkfsldkj sdjlkfsldkj sdjlkfsldkj sdjlkfsldkj sdjlkfsldkj sdjlkfsldkjsdjlkfsldkj sdjlkfsldkj sdjlkfsldkj sdjlkfsldkj sdjlkfsldkj sdjlkfsldkj sdjlkfsldkj sdjlkfsldkj sdjlkfsldkj sdjlkfsldkjsdjlkfsldkj sdjlkfsldkj sdjlkfsldkj sdjlkfsldkj sdjlkfsldkj sdjlkfsldkj sdjlkfsldkj sdjlkfsldkj sdjlkfsldkj sdjlkfsldkjsdjlkfsldkj sdjlkfsldkj sdjlkfsldkj sdjlkfsldkj sdjlkfsldkj sdjlkfsldkj sdjlkfsldkj sdjlkfsldkj sdjlkfsldkj sdjlkfsldkjsdjlkfsldkj sdjlkfsldkj sdjlkfsldkjsdjlkfsldkj sdjlkfsldkj sdjlkfsldkj sdjlkfsldkj sdjlkfsldkj sdjlkfsldkj sdjlkfsldkjsdjlkfsldkj sdjlkfsldkj sdjlkfsldkjsdjlkfsldkj sdjlkfsldkj sdjlkfsldkj sdjlkfsldkj sdjlkfsldkj sdjlkfsldkj sdjlkfsldkjsdjlkfsldkj sdjlkfsldkj sdjlkfsldkjsdjlkfsldkj sdjlkfsldkj sdjlkfsldkj sdjlkfsldkj sdjlkfsldkj sdjlkfsldkj sdjlkfsldkjsdjlkfsldkj sdjlkfsldkj sdjlkfsldkjsdjlkfsldkj sdjlkfsldkj sdjlkfsldkj sdjlkfsldkj sdjlkfsldkj sdjlkfsldkj sdjlkfsldkjsdjlkfsldkj sdjlkfsldkj sdjlkfsldkjsdjlkfsldkj sdjlkfsldkj sdjlkfsldkj sdjlkfsldkj sdjlkfsldkj sdjlkfsldkj sdjlkfsldkjsdjlkfsldkj sdjlkfsldkj sdjlkfsldkjsdjlkfsldkj sdjlkfsldkj sdjlkfsldkj sdjlkfsldkj sdjlkfsldkj sdjlkfsldkj sdjlkfsldkjsdjlkfsldkj sdjlkfsldkj sdjlkfsldkj",
  },
  {
    name: "File 4",
    subject: "Subject",
    id: "4",
    date_created: "10/12/23",
    date_accessed: "10/13/23",
    text: "sdjlkfsldkj sdjlkfsldkj sdjlkfsldkj sdjlkfsldkj sdjlkfsldkj sdjlkfsldkj sdjlkfsldkjsdjlkfsldkj sdjlkfsldkj sdjlkfsldkj sdjlkfsldkj sdjlkfsldkj sdjlkfsldkj sdjlkfsldkj sdjlkfsldkj sdjlkfsldkj sdjlkfsldkjsdjlkfsldkj sdjlkfsldkj sdjlkfsldkj sdjlkfsldkj sdjlkfsldkj sdjlkfsldkj sdjlkfsldkj sdjlkfsldkj sdjlkfsldkj sdjlkfsldkjsdjlkfsldkj sdjlkfsldkj sdjlkfsldkj sdjlkfsldkj sdjlkfsldkj sdjlkfsldkj sdjlkfsldkj sdjlkfsldkj sdjlkfsldkj sdjlkfsldkjsdjlkfsldkj sdjlkfsldkj sdjlkfsldkj sdjlkfsldkj sdjlkfsldkj sdjlkfsldkj sdjlkfsldkj sdjlkfsldkj sdjlkfsldkj sdjlkfsldkjsdjlkfsldkj sdjlkfsldkj sdjlkfsldkjsdjlkfsldkj sdjlkfsldkj sdjlkfsldkj sdjlkfsldkj sdjlkfsldkj sdjlkfsldkj sdjlkfsldkjsdjlkfsldkj sdjlkfsldkj sdjlkfsldkjsdjlkfsldkj sdjlkfsldkj sdjlkfsldkj sdjlkfsldkj sdjlkfsldkj sdjlkfsldkj sdjlkfsldkjsdjlkfsldkj sdjlkfsldkj sdjlkfsldkjsdjlkfsldkj sdjlkfsldkj sdjlkfsldkj sdjlkfsldkj sdjlkfsldkj sdjlkfsldkj sdjlkfsldkjsdjlkfsldkj sdjlkfsldkj sdjlkfsldkjsdjlkfsldkj sdjlkfsldkj sdjlkfsldkj sdjlkfsldkj sdjlkfsldkj sdjlkfsldkj sdjlkfsldkjsdjlkfsldkj sdjlkfsldkj sdjlkfsldkjsdjlkfsldkj sdjlkfsldkj sdjlkfsldkj sdjlkfsldkj sdjlkfsldkj sdjlkfsldkj sdjlkfsldkjsdjlkfsldkj sdjlkfsldkj sdjlkfsldkjsdjlkfsldkj sdjlkfsldkj sdjlkfsldkj sdjlkfsldkj sdjlkfsldkj sdjlkfsldkj sdjlkfsldkjsdjlkfsldkj sdjlkfsldkj sdjlkfsldkj",
  },
  {
    name: "File 5",
    subject: "Subject",
    id: "5",
    date_created: "10/12/23",
    date_accessed: "10/13/23",
    text: "sdjlkfsldkj sdjlkfsldkj sdjlkfsldkj sdjlkfsldkj sdjlkfsldkj sdjlkfsldkj sdjlkfsldkjsdjlkfsldkj sdjlkfsldkj sdjlkfsldkj sdjlkfsldkj sdjlkfsldkj sdjlkfsldkj sdjlkfsldkj sdjlkfsldkj sdjlkfsldkj sdjlkfsldkjsdjlkfsldkj sdjlkfsldkj sdjlkfsldkj sdjlkfsldkj sdjlkfsldkj sdjlkfsldkj sdjlkfsldkj sdjlkfsldkj sdjlkfsldkj sdjlkfsldkjsdjlkfsldkj sdjlkfsldkj sdjlkfsldkj sdjlkfsldkj sdjlkfsldkj sdjlkfsldkj sdjlkfsldkj sdjlkfsldkj sdjlkfsldkj sdjlkfsldkjsdjlkfsldkj sdjlkfsldkj sdjlkfsldkj sdjlkfsldkj sdjlkfsldkj sdjlkfsldkj sdjlkfsldkj sdjlkfsldkj sdjlkfsldkj sdjlkfsldkjsdjlkfsldkj sdjlkfsldkj sdjlkfsldkjsdjlkfsldkj sdjlkfsldkj sdjlkfsldkj sdjlkfsldkj sdjlkfsldkj sdjlkfsldkj sdjlkfsldkjsdjlkfsldkj sdjlkfsldkj sdjlkfsldkjsdjlkfsldkj sdjlkfsldkj sdjlkfsldkj sdjlkfsldkj sdjlkfsldkj sdjlkfsldkj sdjlkfsldkjsdjlkfsldkj sdjlkfsldkj sdjlkfsldkjsdjlkfsldkj sdjlkfsldkj sdjlkfsldkj sdjlkfsldkj sdjlkfsldkj sdjlkfsldkj sdjlkfsldkjsdjlkfsldkj sdjlkfsldkj sdjlkfsldkjsdjlkfsldkj sdjlkfsldkj sdjlkfsldkj sdjlkfsldkj sdjlkfsldkj sdjlkfsldkj sdjlkfsldkjsdjlkfsldkj sdjlkfsldkj sdjlkfsldkjsdjlkfsldkj sdjlkfsldkj sdjlkfsldkj sdjlkfsldkj sdjlkfsldkj sdjlkfsldkj sdjlkfsldkjsdjlkfsldkj sdjlkfsldkj sdjlkfsldkjsdjlkfsldkj sdjlkfsldkj sdjlkfsldkj sdjlkfsldkj sdjlkfsldkj sdjlkfsldkj sdjlkfsldkjsdjlkfsldkj sdjlkfsldkj sdjlkfsldkj",
  },
  {
    name: "File 6",
    subject: "Subject",
    id: "6",
    date_created: "10/12/23",
    date_accessed: "10/13/23",
    text: "sdjlkfsldkj sdjlkfsldkj sdjlkfsldkj sdjlkfsldkj sdjlkfsldkj sdjlkfsldkj sdjlkfsldkjsdjlkfsldkj sdjlkfsldkj sdjlkfsldkj sdjlkfsldkj sdjlkfsldkj sdjlkfsldkj sdjlkfsldkj sdjlkfsldkj sdjlkfsldkj sdjlkfsldkjsdjlkfsldkj sdjlkfsldkj sdjlkfsldkj sdjlkfsldkj sdjlkfsldkj sdjlkfsldkj sdjlkfsldkj sdjlkfsldkj sdjlkfsldkj sdjlkfsldkjsdjlkfsldkj sdjlkfsldkj sdjlkfsldkj sdjlkfsldkj sdjlkfsldkj sdjlkfsldkj sdjlkfsldkj sdjlkfsldkj sdjlkfsldkj sdjlkfsldkjsdjlkfsldkj sdjlkfsldkj sdjlkfsldkj sdjlkfsldkj sdjlkfsldkj sdjlkfsldkj sdjlkfsldkj sdjlkfsldkj sdjlkfsldkj sdjlkfsldkjsdjlkfsldkj sdjlkfsldkj sdjlkfsldkjsdjlkfsldkj sdjlkfsldkj sdjlkfsldkj sdjlkfsldkj sdjlkfsldkj sdjlkfsldkj sdjlkfsldkjsdjlkfsldkj sdjlkfsldkj sdjlkfsldkjsdjlkfsldkj sdjlkfsldkj sdjlkfsldkj sdjlkfsldkj sdjlkfsldkj sdjlkfsldkj sdjlkfsldkjsdjlkfsldkj sdjlkfsldkj sdjlkfsldkjsdjlkfsldkj sdjlkfsldkj sdjlkfsldkj sdjlkfsldkj sdjlkfsldkj sdjlkfsldkj sdjlkfsldkjsdjlkfsldkj sdjlkfsldkj sdjlkfsldkjsdjlkfsldkj sdjlkfsldkj sdjlkfsldkj sdjlkfsldkj sdjlkfsldkj sdjlkfsldkj sdjlkfsldkjsdjlkfsldkj sdjlkfsldkj sdjlkfsldkjsdjlkfsldkj sdjlkfsldkj sdjlkfsldkj sdjlkfsldkj sdjlkfsldkj sdjlkfsldkj sdjlkfsldkjsdjlkfsldkj sdjlkfsldkj sdjlkfsldkjsdjlkfsldkj sdjlkfsldkj sdjlkfsldkj sdjlkfsldkj sdjlkfsldkj sdjlkfsldkj sdjlkfsldkjsdjlkfsldkj sdjlkfsldkj sdjlkfsldkj",
  },
];
